export const UPDATE_WATER_CONSUMPTION = "UPDATE_WATER_CONSUMPTION";
export const UPDATE_WORKOUT_HOURS = "UPDATE_WORKOUT_HOURS";
export const UPDATE_SLEEP_HOURS = "UPDATE_SLEEP_HOURS";
export const GET_UPDATED_LIST = "GET_UPDATED_LIST";